### PR TITLE
added --3D-path-var argument 

### PR DESCRIPTION
**Pull request by Ing-Dom**
to set the 3d path in the footprint to a KiCAD Path variable

command line:
easyeda2kicad --full --lcsc_id=C2040 --output ~/libs/my_lib --overwrite  --3D-path-var EASYEDALIB_3D
result:
`(model "${EASYEDALIB_3D}/LQFN-56_L7.0-W7.0-P0.4-EP.wrl"`

with EASYEDALIB_3D set to ~/libs/my_lib.3dshapes in KiCAD.

With this option you can add the lib to a different machine with other paths.

### CODE REVIEW

**Comment by uPesy** [comment]
These PR suggest a uniq path var when using custom path #84

**Comment by Ing-Dom** [comment]
while the path to the footprints and the path to the symbol dir is a setting of every KiCAD installation that can be individually set by the user, the 3D-path is hardcoded.
When you look at the footprints shipped with KiCAD they use someting like
${KICAD6_3DMODEL_DIR}/LED_SMD.3dshapes/LED_0603_1608Metric.wrl

For my libs I add a seperate KiCAD var like EASYEDALIB_DIR to KiCAD settings.
I also use this path in the 3D-path of the footprint and it can also used when adding symbol or footprint libs.

this PR is not up-to-date, because I changed something to have not a path var for 3d but for the whole lib.

**Comment by Ing-Dom** [comment]
fyi thats how I call the easyeda2kicad

cmd /c "`"C:\Program Files\KiCad\7.0\bin\python.exe`" -m easyeda2kicad --full --lcsc_id=$part --output `"$currentDir\EasyEDALib`" --overwrite --3D-path-var `${EASYEDALIB_DIR}/EasyEDALib.3dshapes"

**Comment by uPesy** [comment]
> this PR is not up-to-date, because I changed something to have not a path var for 3d but for the whole lib.
Yes it's seems the best idea, it will be the same request than PR #84 
Could you push your updated code to merge  your PR ?
Kind regards

**Pull request closed without merging**
