### PR TITLE
Upgrade to Pydantic V2

### PR DESCRIPTION
**Pull request by mawildoer**
Pydantic V2 has breaking API changes, but provides a tool to automatically refactor code. 
This commit bumps the Pydantic version and upgrades the API calls using their tool. 
Migration guide: https://docs.pydantic.dev/2.0/migration/

## Validation

- `tox` passes
- smoke tested by downloading [a component](https://jlcpcb.com/partdetail/171784-SM04B_SRSS_TB_LF_SN/C160404) and it produced the desired results

### CODE REVIEW

**Comment by uPesy** [comment]
Thanks @mawildoer for your PR !
What is the benefit of Pydantic V2 that can be used in easyeda2kicad ?

**Comment by mawildoer** [comment]
Something has to change, because a clean install automatically grabs the latest version of Pydantic, which isn't backwards compatible. Given the [requirements spec for Pydantic](https://github.com/uPesy/easyeda2kicad.py/pull/96/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L6), `>=1.5`.

One option is to change this spec to match [compatible releases](https://peps.python.org/pep-0440/#compatible-release) `~=1.5`, but in my experience that often means projects are left with old versions and eventually become incompatible with the other content in a larger venv.

Instead, by upgrading early we can support more combinations of requirements with other packages.

**Comment by uPesy** [comment]
There is an error in the CI pipeline with `pre-commit`, i don't understand why ...

**Comment by mawildoer** [comment]
That is a little strange...

It appears the error is related to the pycln library trying to install an older version of PyYAML. The pycln library has specified in its requirements that it needs PyYAML version less than 6.0.0 but greater than or equal to 5.3.1. However, during the execution, PyYAML version 6.0.1 was installed. When pycln then tried to downgrade PyYAML to 5.4.1, it ran into issues.

I'm less familiar github actions, where's its environment configured?

**Comment by uPesy** [comment]
By forcing python 3.8 version, it seems to work.
By the way, you said that you have made some tests with tox and pytest.
I'm will be very interested to have some basic unit tests by using this tool for easyeda2kicad, but i don't have enough experience with them. Could you create some boilerplate test code with config files to start implementing unit tests for data conversion ?

**Comment by mawildoer** [comment]
Hey mate, sorry I missed this last question you had! Did you ever figure out those unit tests?

**Pull request merged**
